// ejemplo-vuejs/src/components/Usuario.vue
<template>
  <div>
    <!-- <p>{{apellido}}, {{nombre}}</p> -->
    <!-- <p>{{usuario.apellido}}, {{usuario.nombre}}</p> -->
    <p>{{nombreCompleto}}</p>
    <router-link :to="rutaInfo">Info</router-link>
    <router-link :to="rutaEditar">Editar</router-link>
  </div>
</template>

<script>
export default {
  // props: ['nombre', 'apellido'],
  props: {
    // nombre: {
    //   type: String,
    //   default: 'Mundo',
    // },
    // apellido: {
    //   type: String,
    //   required: true
    // }
    usuario: {
      type: Object,
      required: true
    }
  },
  computed: {
    nombreCompleto() {
      // return this.usuario.nombre + ' ' + this.usuario.apellido;
      return `${this.usuario.nombre} ${this.usuario.apellido}`
    },
    rutaEditar() {
      return '/usuarios/' + this.usuario.id + '/editar'
    },
    rutaInfo() {
      return '/usuarios/' + this.usuario.id + '/info'
    }
  }
}
</script>

<style>

</style>

// ejemplo-react/src/components/Usuario.jsx
import React from 'react'
import { Link } from 'react-router-dom'

const Usuario = (props) => {

  const rutaInfo = `/usuarios/${props.usuario.id}/info`
  const rutaEditar = `/usuarios/${props.usuario.id}/editar`

  return (
    <div>
      {props.usuario.name}
      <Link to={rutaInfo}>Info</Link>
      <Link to={rutaEditar}>Editar</Link>
    </div>
  )
}

export default Usuario
