// ejemplo-vuejs/src/components/InfoUsuario.vue
<template>
  <div>
    <h2>Info usuario {{id}}</h2>
  </div>
</template>

<script>
export default {
  props: ['id'],
  watch: {
    '$route'(newVal, oldVal){
      const idUsuario = newVal.params.id
      fetch(`https://jsonplaceholder.typicode.com/users/${idUsuario}`)
        .then(resp => {
          return resp.json()
        })
        .then(datos => {
          console.log(datos);
        })
    }
  }
}
</script>

<style>

</style>

// ejemplo-react/src/pages/InfoUsuario.jsx
import React, { useState, useEffect } from 'react'
import { URL } from './Usuarios'

const InfoUsuario = (props) => {

  const [usuario, setUsuario] = useState(null)
  const [mostrar, setMostrar] = useState(false);

  useEffect(() => {
    console.log('Pasa por aqui')
    fetch(`${URL}/${props.match.params.id}`)
      .then(resp => resp.json())
      .then(datos => {
        // console.log(datos)
        setUsuario(datos);
      })
  }, [props.match.params.id])

  useEffect(() => {
    if(mostrar) {
      alert('Mostrar es true')
    }
  }, [mostrar])

  return (
    <div>
      <h2>Info Usuario ({props.match.params.id})</h2>
      <pre>{JSON.stringify(usuario, null, 4)}</pre>
      <button type="button" onClick={() => setMostrar(!mostrar)}>Toggle mostrar</button>
      {mostrar ? <p>Se muestra</p> : null}
    </div>
  )
}

export default InfoUsuario
